### ISSUE TITLE
Error rendering

### ISSUE THREAD

**Issue by Knaky41** [LucasArona/larona-epict-panel#1]
Hi,

I'm trying to use your module to render some Elastic data.

Is it compatible with Elastic ?

Cheers.

**Comment by LucasArona** [comment]
Hello,

I have not tested the plugin with ElasticSearch, only with MySQL datasource and TestData DB provided by Grafana.
However, it should works with any time series data source.

Can you give some details about the error you are experiencing ?

thanks

**Comment by Knaky41** [comment]
Hi,

Nevermind, I'm able to get numerical values like numbers.

Do you if it's possible to get a string value ? For example, when you use metric beat on windows, you can get the state of a process like "running", "stopped"...

Cheers.

**Comment by LucasArona** [comment]
Ok, I see. Unfortunately, only numeric values are supported at the moment.

**Comment by eoraham** [comment]
Hello,

Do you know if the plugin is now compatible with Elasticsearch 7.2?
I get "N/A" instead of a numeric value. My Lucene query seems OK as the result is correctly displayed in an other type of Grafana panel.

Thank you!
