### ISSUE TITLE
Cannot get data on Epict panel

### ISSUE THREAD

**Issue by jrashev** [LucasArona/larona-epict-panel#10]
Hi,

i am trying to use epict panel and have a simple query, however the data is not presented.

Here is the query and the result returned (it is value)

![image](https://user-images.githubusercontent.com/7542600/56713257-0455b280-673a-11e9-9c64-6429fd6f3da3.png)

Here is the box configuration
![image](https://user-images.githubusercontent.com/7542600/56713315-1cc5cd00-673a-11e9-942a-2e7fc4af17d3.png)

is there anything specific that need to be used when setting the name of the series?

br

Jordan

**Comment by LucasArona** [comment]
Hello,

It seems that you are using MySQL datasource. However, you set the format as "Table" (first screenshot). We can't show tabular data, you have to select Format as "Time Series".

Your query is not based on time series data, but this is not a problem: when you select Format as Time Series, Grafana will insert a pre-defined query in the UI, the important thing here is to return a column named "time", another named "metric" and a last one: "value".

For the "time" column, you can use NOW() in your query (unless you already have a date/time column for your measurements), for "metric" you can write "Counter4" for example and "value" should be the value you want to display.

Your query should look almost like this:

```
SELECT
  NOW() as time
  Counter4 as value,
  'Counter4' as metric
FROM Summary
WHERE DevEUI=....
```

I don't have MySQL datasource at the moment, but if you need further assistance don't hesitate to ask.

**Comment by jrashev** [comment]
Hello Lucas,

Thank you for the hint and for the support,

now it works perfectly as described.

br

Jordan
