### ISSUE TITLE
Error rendering in PNG

### ISSUE THREAD

**Issue by Knaky41** [LucasArona/larona-epict-panel#13]
Hi,

First, thank you for this amazing module :)

I just have one issue, I'm trying to render in PNG via the Grafana API.

I get this error :

> error rendering PNGs in parralel for dash {Title:Test Description: VariableValues: Rows:[] Panels:[{Id:2 Type:larona-epict-panel Title:}]}: error getting panel {Id:2 Type:larona-epict-panel Title:}: Error obtaining render: 500 Internal Server Error

In addition, this is the Grafana logs :

> t=2019-09-11T09:27:36+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/{{ctrl.processedBgURL}} status=404 remote_addr=[::1] time_ms=0 size=32287 referer="http://localhost:8080/d-solo/m6KaFb5Zk/_?orgId=1&from=now%2Fd&height=500&panelId=2&theme=light&to=now&width=1000&render=1"​

> t=2019-09-11T09:28:35+0200 lvl=info msg="Rendering timed out" logger=rendering​

> t=2019-09-11T09:28:35+0200 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="Timeout error. You can set timeout in seconds with &timeout url parameter"​

> t=2019-09-11T09:28:35+0200 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/m6KaFb5Zk/_ status=500 remote_addr=[::1] time_ms=62059 size=1856 referer=​

I'm using the latest grafana version on Windows with Elastic datasource.

Thanks 👍

**Comment by LucasArona** [comment]
Hello,

thanks for your feedback.
Can you confirm that the rendering is OK if you load the dashboard in your browser (without using the API ?) and that the "Background URL" field has a valid URL ?

**Comment by Knaky41** [comment]
Hi,

yes the rendering is fine on the dashboard including the background url.

Thanks.

**Comment by balpak** [comment]
Hi Lucas,

I confirm similar messages in the log. Rendering is fine and works as expected.

`Jan  9 15:11:58 GRF-637 grafana-server: t=2020-01-09T15:11:58+0200 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=viewer method=GET path=/{{ctrl.processedBgURL}} status=404 remote_addr=192.168.168.12 time_ms=3 size=36560 referer="http://192.168.168.115:3000/d/xRVM2IFZz/sugp-overview?orgId=1"`

Let me know if I could provide more information.

Regards,
Yuri

**Comment by LucasArona** [comment]
Hello,
The plugin has been entirely rewritten for v2.0.0, if you still need png rendering with epict-panel you can try again with v2.0.0 and see if it works as expected now, if not, feel free to open this issue again.

Best regards,
Lucas
