### ISSUE TITLE
New Features 

### ISSUE THREAD

**Issue by lucioaquino** [LucasArona/larona-epict-panel#2]
Congratulations Lucas . 
 
 You made a very good Job here . 

 One good feature to add  some things like the "options " of  the Single Stat Panel . 

- Prefix / Postfix
- Thresholds with change of colors and blink 
- Link Clicable 

Like one big diagram with many point of attention if something gone wrong ,  live as point of start for others dashboards 

Very good Job

.

**Comment by LucasArona** [comment]
Thanks for your feedback and for your ideas ;-)
In the meantime, the postfix already exists and is called "suffix" in the options.

**Comment by LucasArona** [comment]
Version 1.1.0 shipped today:

- [X] You can now add a Link to your boxes.
- [X] Added the option to display a prefix in addition to the suffix
- [X] Add the thresholds feature (colors and blink)
