### ISSUE TITLE
Grafana 6.x

### ISSUE THREAD

**Issue by skydiablo** [LucasArona/larona-epict-panel#25]
Hi,
i have installed your plugin like this:

```
user@host:~$ sudo -u grafana grafana-cli plugins install larona-epict-panel
installing larona-epict-panel @ 1.2.2
from: https://grafana.com/api/plugins/larona-epict-panel/versions/1.2.2/download
into: /var/lib/grafana/plugins

✔ Installed larona-epict-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>

user@host:~$ sudo systemctl restart grafana-server
```

and yes, the epict plugin is shown in the plugin overview, but i can not select this plugin for a new visualization panel?!

my grafana version is: v6.7.2

**Comment by LucasArona** [comment]
Hello,
I just did a test with 6.7.2 and I can see the plugin, can you try to clear your browser's cache ?
![image](https://user-images.githubusercontent.com/26776624/78710905-680ac880-7916-11ea-9b89-17caa5737557.png)

**Comment by skydiablo** [comment]
indeed! one day layter, without any changes, the icon is appear! thx!
