### ISSUE TITLE
Use Prometheus TimeSeries

### ISSUE THREAD

**Issue by skydiablo** [LucasArona/larona-epict-panel#26]
there is no chance to handle prometheus time-series? i always get an "N/A" result ?

![grafik](https://user-images.githubusercontent.com/956423/78869182-70612180-7a44-11ea-9cb3-a67613aa7678.png)

![grafik](https://user-images.githubusercontent.com/956423/78869240-88d13c00-7a44-11ea-9517-53dd3a59aaca.png)

**Comment by LucasArona** [comment]
Hello,

v2.0.0 released today is compatible and has been tested with Prometheus datasources.

Best regards,
Lucas
