### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by seven8023** [LucasArona/larona-epict-panel#27]
Hi.   great appreciate for this epic-panel. 👍 

Is it possible to add  a  html box  ^_^    which allows to display external content in a panel.

I mean the box to display HTML text.    So We can write HTML CODE, instead of assigning metrics for the palcehoder.    

And  if support Ajax  that  would be awesome ~. 

hope I am making sense

For example

1:    `<img scr="http://1.2.3.4/a.gif">`         the box will show  a.gif   

2:    add netdata badges  to show in the panel. 

        https://learn.netdata.cloud/docs/agent/web/api/badges/

```
   <a href="#">
     <img src="https://registry.my-netdata.io/api/v1/badge.svg?chart=system.cpu"></img>
   </a>
```

 <a href="#">
     <img src="https://registry.my-netdata.io/api/v1/badge.svg?chart=system.cpu"></img>
   </a>

**Comment by LucasArona** [comment]
Hello,

thanks for your suggestion, I like the idea of being able to add a custom url for the image.

Best regards
Lucas

**Comment by LucasArona** [comment]
The upcoming v2.0.5 allows you to specify a custom image url to be shown in the boxes.
