### ISSUE TITLE
AngularJS vs. React

### ISSUE THREAD

**Issue by balpak** [LucasArona/larona-epict-panel#29]
Hi Lucas,

As you know since Grafana 6.x, panels are ReactJS components. Do you have any plans to re-write your plugin to React or will continue development using AngularJS?

Thanks,

**Comment by LucasArona** [comment]
Hello,

yes, I started rewriting everything in React, it'll be v2.0.0. In the meantime, it should still work with recent versions of Grafana.

Best regards
Lucas

**Comment by balpak** [comment]
Good news! Maybe you could add one small feature as well - option to have background for the value like shown below on the right?

Thanks.

![Capture](https://user-images.githubusercontent.com/59735593/84590483-65a57d00-ae37-11ea-8515-37c7ed0cca14.PNG)

**Comment by balpak** [comment]
Sorry, clicked on the wrong button.
