### ISSUE TITLE
grafana 7.1.5  problem associating metric

### ISSUE THREAD

**Issue by BasilBibi** [LucasArona/larona-epict-panel#30]
Hi,
Hopefully I am doing something wrong - I cannot get any metrics to associate with a box.
Please help !

[
![ePictGrafana7 1 5 problem](https://user-images.githubusercontent.com/4756910/94897715-1dfb3d80-0488-11eb-926d-6b350097a81f.png)
](url)

**Comment by LucasArona** [comment]
Hello,
I'm working on publishing update 2.0 of the plugin, it should be ready soon.
This should improve data sources compatibility.

In the meantime, can you confirm that you can see results in Query inspector?

**Comment by BasilBibi** [comment]
Hi Lucas, Thanks for the quick response. Yes I can confirm - results are visible in the query inspector.

**Comment by MadWalnut** [comment]
I am experiencing the same thing with an InfluxDB Flux Query. It always shows "N/A".

**Comment by LucasArona** [comment]
@BasilBibi @MadWalnut v2.0 should be available before the end of the year. Still finalizing it, Grafana has made a lot of changes in his framework not so long ago.

**Comment by LucasArona** [comment]
v2.0.0 has been approved by Grafana today and is available online https://grafana.com/grafana/plugins/larona-epict-panel
