### ISSUE TITLE
Is there a basic tutorial for new users

### ISSUE THREAD

**Issue by Robb-Greathouse** [LucasArona/larona-epict-panel#31]
I'm new to epict and grafana.  I added epict to my plugins.  But can't figure out how to add a panel based on epict. 

This is a more basic question than you are probably used to.

**Comment by LucasArona** [comment]
Here is a gif showing how you can create a basic dashboard with epict panel, hope it helps :
![demo](https://user-images.githubusercontent.com/26776624/100016777-3cbbe780-2dda-11eb-9b97-97ff211722d5.gif)

**Comment by Robb-Greathouse** [comment]
Thanks!

**Comment by manggis123** [comment]
Hi, 

I'm also beginner with grafana.  I'm just installed epict today.

I'm using Mysql.  My value doesn't appear on box.  I thought there are some problem with my query.  Could you help me? 

![image](https://user-images.githubusercontent.com/75624215/101366617-1caf1c80-38e0-11eb-9110-cf96a90e31e4.png)

Thanks.

**Comment by LucasArona** [comment]
@manggis123 can you select "Time series" instead of "Table" in "Format as" ? The query seems to be correct.

**Comment by manggis123** [comment]
Hi @LucasArona, 

I'm already changed format as to Time Series, but it still same.  The result still no appear.

![image](https://user-images.githubusercontent.com/75624215/101421313-fbc1e800-392e-11eb-8694-8d1944ff433e.png)

My Temperature table:

![image](https://user-images.githubusercontent.com/75624215/101421351-11371200-392f-11eb-882c-d43f080ffa7d.png)


Thanks

**Comment by manggis123** [comment]
I'm trying not filter the data by time, query inspect return 1 row but the value still not appear on the dedicated box.

![image](https://user-images.githubusercontent.com/75624215/101430937-f40b3f00-3940-11eb-825d-79868c0acb78.png)

**Comment by manggis123** [comment]
Finally, I had solved my problem.

A few mistake as highlighted, reference for beginners like me =)

![image](https://user-images.githubusercontent.com/75624215/101442197-c11f7600-3955-11eb-8e13-943872cd496e.png)

**Comment by manggis123** [comment]
Hi @LucasArona ,

Is it possible Epict to cater scenario as this image:

![image](https://user-images.githubusercontent.com/75624215/101442432-4d319d80-3956-11eb-94f7-512be811af63.png)

In select statement, we only query 3 columns which is time, metric and value.  Type of value column must integer.  How if I want to appear the status varchar such as "OK", "MALFUNTION" etc.

I stored my data as below:

![image](https://user-images.githubusercontent.com/75624215/101442857-1ad47000-3957-11eb-8838-b116e06556a4.png)

1 - OK
2 - Malfunction

So, my problem is how to appear Item column and Status column using Epict.

Thanks.

**Comment by LucasArona** [comment]
Hello,

mapping a value to a status label is not yet implemented, maybe in a future release.

Thanks,
Best regards

**Comment by manggis123** [comment]
Thanks @LucasArona .
