### ISSUE TITLE
Automated set-up

### ISSUE THREAD

**Issue by Robb-Greathouse** [LucasArona/larona-epict-panel#32]
We are deploying to temporary clouds.  Is there a way to script the Epict plugin so that a user won't have to go through the manual process of loading background photo and creating boxes and queries each time?

**Comment by LucasArona** [comment]
Yes, you can use Grafana's Dashboard API: https://grafana.com/docs/grafana/latest/http_api/dashboard/
A dashboard is stored as JSON, the easiest way is to start with an existing dashboard and show the JSON model (Dashboard settings -> JSON Model).

You can take a look at [Provisioning Grafana](https://grafana.com/docs/grafana/latest/administration/provisioning) too, it's another way to provision dashboard with config files.
