### ISSUE TITLE
Gaps in Prometheus data cause panel to fail

### ISSUE THREAD

**Issue by Jii-Hoo** [LucasArona/larona-epict-panel#34]
Great plugin! However, I hit to an issue in case Prometheus time-series data has a gap during the selected time period (which can happen occasionally, as I'm federating data from multiple lower level Prometheus servers). This causes almost always the panel to fail.

As an example, I had below time series which worked OK on regular line graph:

![line_graph](https://user-images.githubusercontent.com/28671278/106053723-cac29000-60f3-11eb-8530-58eff9010e15.png)

With epict, this caused following error in panel in case the time period included the gap.

![epict](https://user-images.githubusercontent.com/28671278/106054015-28ef7300-60f4-11eb-9d0f-8a19444638a6.PNG)

The only way to get rid of this was either to change the time period or wait that the gap got out of the current one. And even after that only reloading the page completely in browser got the panel working again.

**Comment by Jii-Hoo** [comment]
As an additional observation, same issue seem to also come occasionally up in case shorter (1-5m) time period is used, but then reload typically helps. I'm not sure if the question is about issues with fetching data fast enough from Prometheus in that case. using longer time period (30-60m) seems to help, but that then may hit easier to issues with gaps in data,

**Comment by LucasArona** [comment]
Hello,

thanks for the feedback!
I'm trying to repro this issue: I have a serie with missing data, but I'm still able to see the latest data frame:
![image](https://user-images.githubusercontent.com/26776624/106065264-5a1f7180-60fb-11eb-9d14-30d216f44687.png)

Can you click on "Query Inspector" -> "Data" tab, then scroll at the bottom and share a screenshot of what you can see ? for example: 
![image](https://user-images.githubusercontent.com/26776624/106065480-ab2f6580-60fb-11eb-95c5-9e140f66378a.png)

I'm able to get an error if the **latest** data frame is null, but this leads to a different error:
![image](https://user-images.githubusercontent.com/26776624/106065692-f21d5b00-60fb-11eb-9069-a1a46cb3bbbf.png)

Best,
Lucas

**Comment by Jii-Hoo** [comment]
Query inspector did not show any gaps in the Data-tab, while the issue occurred. However, the tab shows data for only one of the 6 queries I have in the panel and in this case there were gaps in 2 of the queries not visible in tab.

I have to still try to try this more to see if the issue comes up even without gaps in data and try also to reduce amount of queries in panel. However, one thing which makes this bit difficult to check is the fact that there are two Prometheus-instances for HA purposes. Both are independent from each other and gap in data may occur only in the one of them. Thus it does not necessarily come up always up as queries from Grafana are distributed over both two instances

**Comment by Jii-Hoo** [comment]
I was able to isolate the issue:

- Set time range to last 1 minute, so that Data-tab in query inspector showed values only for last two minutes with the query visible there.
- Refreshed the panel and checked contents of Data-tab after it.

As a result, everything seems to work if Data-tab shows values for both minutes. However, if the last one is missing, I get the error in panel:

![image](https://user-images.githubusercontent.com/28671278/106121001-ba47ff00-615f-11eb-9004-4ae033dea370.png)

So I would guess that this is not about the gaps in the whole dataset after all, but about the missing value for the last minute. I.e. the same which you observed above, although the error which I get is different.

**Comment by Jii-Hoo** [comment]
Well, this is interesting. I'm typically using Firefox (v85 currently), but decided to try also with Edge. I got the same error as you did with it:

![image](https://user-images.githubusercontent.com/28671278/106389085-3b1a2b80-63ea-11eb-9044-20b7f764f7a1.png)

But at the end the question is about the same issue, I guess.

**Comment by Jii-Hoo** [comment]
When looking to code, I think that the issue simply comes from this line in getBoxValue-function at EpictPanel.tsx.

`let lastValue = fields?.values.get(fields.values.length - 1).toFixed(decimals).toString();`

If the latest value is occasionally null, then also 

fields?.values.get()

will return null and thus the above error. Perhaps in such case previous value should be read instead, as otherwise there could be N/A values constantly coming and going. Of course, if also previous value would be null, then N/A would be an obvious choice.

**Comment by LucasArona** [comment]
Thanks for the feedback, I'll check this out.
I did some tests with Firefox and I was able to see the error message you provided, it's also related to the fact that the last value is null, indeed.

**Comment by LucasArona** [comment]
fixed in upcoming update 2.0.1, currently pending approval by Grafana

**Comment by LucasArona** [comment]
2.0.1 is online now!
