### ISSUE TITLE
Missing logo file

### ISSUE THREAD

**Issue by scottmelhop** [LucasArona/larona-epict-panel#36]
I got this error installing 2.0.1
`2021-03-04 08:02:47.514 CETError: ✗ failed to extract plugin archive: failed to extract file: failed to open file: open /var/lib/grafana/plugins/larona-epict-panel/img/logo.svg: no such file or directory
`

**Comment by LucasArona** [comment]
Which version of Grafana ?
Can you try again, because this file is in the archive and I can't repro the issue.

**Comment by tseplak** [comment]
I also just ran into this error. Using Grafana 7.1.5.
