### ISSUE TITLE
InfluxDB Unable to select separate queries

### ISSUE THREAD

**Issue by damieliel** [LucasArona/larona-epict-panel#37]
I am reading a bunch of data in from InfluxDB and I cannot figure out how to split it up into separate queries that I can select using ePict Panel.

Any ideas?
Thanks,
Damiel
![image](https://user-images.githubusercontent.com/27155896/110369603-a0c88b80-8018-11eb-8d96-604b074e8f49.png)

**Comment by LucasArona** [comment]
Can you give me a "preview" of what your dataset looks like ?

You probably need to Group By tag, but I may be able to provide better assistance if I you can show me a preview of your dataset, it would be cool if you can post a screenshot of what you can see in the Query Inspector, like that:

![image](https://user-images.githubusercontent.com/26776624/110375950-e5711880-8052-11eb-81db-9674510cb086.png)


Best regards,
Lucas

**Comment by LucasArona** [comment]
Thanks for the details, I need to fix this in the code. 

The last time I checked influxdb, it was with version 1.x and influxQL... things have evolved and I need to make changes to improve the compatibility of the plugin.

**Comment by damieliel** [comment]
Hi Lucas,
Thanks so much! Keep me posted as it gets updated!

Thanks so much,
Damiel

**Comment by damieliel** [comment]
Hi Lucas,
Just checking in to see if you have been able to make any progress.
Thanks,
Damiel

**Comment by LucasArona** [comment]
Hello,

Yes, I've finally been able to make some progress on this issue in the last few days!
I hope to publish the fix this week...

Would you be interested in testing a beta version before I send the plugin to Grafana, to check that this fixes the issue in your case?

Best,
Lucas

**Comment by damieliel** [comment]
Hi Lucas,
I would love to Beta test it!

Thanks so much!
Damiel

**Comment by LucasArona** [comment]
Thanks for agreeing to test this beta version! 🧪

Here are the instructions:

First, uninstall the existing version of the plugin
```shell
grafana-cli plugins remove larona-epict-panel
```
Then, install the pre-release version of the plugin
```shell
grafana-cli --pluginUrl https://github.com/LucasArona/larona-epict-panel/releases/download/v2.0.2-beta/larona-epict-panel-2.0.2-beta.zip plugins install larona-epict-panel
```
then, restart grafana-server as usual, and check that the version shown in "Plugins" is `2.0.2-beta`, then you can start testing to check if it works as expected.

Keep me posted

Thanks!
Best regards

**Comment by damieliel** [comment]
Hi Lucas,
I am currently using Grafana Cloud - is there any way for me to beta test the plug-in there?

Thanks,
Damiel

**Comment by LucasArona** [comment]
Hello,

No, I don't think you can use "not yet released" plugins on Grafana Cloud.
However, as there are no breaking changes and as that the tests I did on my side look good, I'll release v2.0.2 ASAP

Best,
Lucas

**Comment by LucasArona** [comment]
I sent the update to Grafana 2 days ago, it's now pending review by Grafana.
I will let you know when I have any news about it.

Best,
Lucas

**Comment by damieliel** [comment]
That is great to hear!

Thanks so much,
Damiel

**Comment by damieliel** [comment]
Thanks so much! Working much better now!

**Comment by LucasArona** [comment]
Glad to hear it, thanks for the feedback.
