### ISSUE TITLE
Using Helm3 to configure epict panel

### ISSUE THREAD

**Issue by Robb-Greathouse** [LucasArona/larona-epict-panel#38]
Hi,

Is there any documentation or are there any examples of using Helm 3 to configure and deploy Epict on Grafana?

Thanks

**Comment by LucasArona** [comment]
Hello,

no, but Grafana provides documentation about provisioning Grafana with Config Files, here:
https://grafana.com/docs/grafana/latest/administration/provisioning/

**Comment by Robb-Greathouse** [comment]
Thank you.
