### ISSUE TITLE
Cloned boxes' configuration is not saved

### ISSUE THREAD

**Issue by alehuby** [LucasArona/larona-epict-panel#39]
When cloning a box, the options are not saved. Only options that are changed are updated and saved.

For example, you clone a box set up with metric, suffix, position, font size, threshold, etc. You change the metric and position, but not the rest. You save the panel and dashboard, leave and come back and all the options that were not changed (everything but position and metric) are reset to default.

It somewhat defeats the purpose of cloning.

Happens on both 2.0.1 and 2.0.2-beta.

**Comment by LucasArona** [comment]
Thanks for reporting this!

Can you try with 2.0.3-beta?
https://github.com/LucasArona/larona-epict-panel/releases/download/2.0.3-beta/larona-epict-panel-2.0.3-beta.zip

**Comment by alehuby** [comment]
Works perfectly now :smiley:.

Thanks for the quick fix!
