### ISSUE TITLE
feature / request - make image linkable 

### ISSUE THREAD

**Issue by meeki007** [LucasArona/larona-epict-panel#4]
I love epict-panel ! 
Using it to bring real time display for ammonia compressors.
I have multiple compressors in the motor-room.

It would be nice to be able to click the image and have it goto a http link. This way I can direct to a page of just that compressor. 

Great work.

**Comment by LucasArona** [comment]
Thanks for your feedback 👍

You can already do this, Grafana provides this feature for each panels:
Click on the panel title, then Edit
![image](https://user-images.githubusercontent.com/26776624/53113863-d047f080-3542-11e9-890e-38844b16f683.png)

and Add a Drilldown link ("General" tab):

![image](https://user-images.githubusercontent.com/26776624/53113957-09806080-3543-11e9-8fef-b8f39d932ef3.png)

Best,
Lucas
