### ISSUE TITLE
Not working with local IP

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [LucasArona/larona-epict-panel#42]
Hello,
The plugin does not load an image that is coming from a local instance of apache. The same URL in chrome works fine, but it does not in the plugin.
Url is like `http://192.168.1.2/images/web.jpg` but it does not work even if the endpoint exists. Anything else like `https://www.sudefuturi-magazine.it/wp-content/uploads/2021/01/web.jpg` works.
In this test, the two files are identical.

Thanks

**Comment by LucasArona** [comment]
Hello,

maybe you are accessing your grafana instance using `https` ? The browser will not allow you to load mixed content (`http` resource on an `https` page, typically), you should see an error in your browser's developer tools.

Best regards,
Lucas

**Comment by mirkocomparetti-synesis** [comment]
You are right: grafana is over `https` but apache isn't. And there it is the error in the console.

Thanks!
