### ISSUE TITLE
How to display a string value

### ISSUE THREAD

**Issue by HakamSaffour** [LucasArona/larona-epict-panel#49]
Grafana V8.2.3
ePict Panel V2.0.5

I want to display a string value using ePict Panel, it seems it is only possible to display a numeric value.
Is there a way to display a string value?

![image](https://user-images.githubusercontent.com/11553465/150948882-757ba59c-3fed-48db-ae5d-d1fee2d55ffb.png)

**Comment by LucasArona** [comment]
Yes, it should work, can you double check that you selected the correct Metric in the settings?

![image](https://user-images.githubusercontent.com/26776624/151025970-ceb11345-78bf-4584-830c-ef31f3847be2.png)

Also, can you tell me which datasource you are using?

**Comment by HakamSaffour** [comment]
By clicking on 'Change Metric', I got: 
![image](https://user-images.githubusercontent.com/11553465/151144412-77ccf6bd-25fe-4e85-9903-ac2640cad3aa.png)

Datasource is: MS SQL

Received data looks like this: 
![image](https://user-images.githubusercontent.com/11553465/151144874-0003def5-ff1d-4862-a62d-d0f9471c3997.png)

**Comment by LucasArona** [comment]
Okay, I'm able to reproduce this issue too. I'll work on a fix for a future release.

In the meantime, you can try the following workaround:

Click on `Inspect` -> `Panel JSON` on your panel
![image](https://user-images.githubusercontent.com/26776624/151432684-2d5e5264-3e29-4189-8361-8a7d78acfcbc.png)

Under "boxes" you'll find the settings of the boxes you added on the panel, find the "serie" value corresponding to the box and replace "A-Serie" by "DeviceSN" and click on "Apply"
  
  
![image](https://user-images.githubusercontent.com/26776624/151433163-e3f24cf1-a392-4f54-a61b-d17486d28117.png)

Let me know if this workaround works for you.

**Comment by HakamSaffour** [comment]
Hello,
yes, the work around works. Thanks!
The drawback is, if I used multiple quires (A-Serie, B-Serie, etc.) and replaced them with 'DeviceSN', therefore I have to use unique name for each query.

Looking forward to the bug fix

**Comment by fer-tovar** [comment]
Hello,

I tried using this workaround to show strings, but the Panel stops working:

![image](https://user-images.githubusercontent.com/100443077/169507131-82147bfd-1c51-4cfd-a3d4-f15dc3135269.png)

![image](https://user-images.githubusercontent.com/100443077/169512177-1862864a-acf2-4cff-9237-c9b606c3f074.png)

I am using influxdb as datasource. Could you please help me?
