### ISSUE TITLE
Possible to set image URL from a grafana variable?

### ISSUE THREAD

**Issue by DiscGolfFlyer** [LucasArona/larona-epict-panel#5]
Hey, I really enjoy using your plugin. It provides a touch of flair that I love.

Would you be able to make it so that the image URL can have variables in them? That would make them dynamic on dashboards which would be awesome.

Thank you for providing this for us to use!

**Comment by LucasArona** [comment]
Hello,
thank you for your feedback and for the suggestion. I added your idea to the to-do list 👍

Best,
Lucas

**Comment by LucasArona** [comment]
v1.2.1 published today:
You can now use variables in the URL fields (for the background URL and the clickable link in the boxes)
