### ISSUE TITLE
Suggestion for add an option to don't display the white box on the right bottom corner

### ISSUE THREAD

**Issue by simonzhang98** [LucasArona/larona-epict-panel#52]
Hi,

thank you very much for the ePict plugin.

Could the ePict plugin add an option to don't display the white box on the right bottom corner.

Thanks a lot and best regards!

**Comment by LucasArona** [comment]
Hello,

Thanks for the feedback! that's a bug, I don't think this was shown with previous versions of Edge/Chrome/Chromium. I'll fix this in the next release.

Best regards
