### ISSUE TITLE
Suggestion/Feature for next version

### ISSUE THREAD

**Issue by Coding-Mike** [LucasArona/larona-epict-panel#53]
It would be great to get an indicator in the "Change Metric" selection box (Drop Down) that shows if the metric is already used by any other box.

This would make it much easier to connect the boxes with the metrics.

Maybe also a sorting like all "free" metrics first and then all used ones.

Kind regards
Michael

**Comment by LucasArona** [comment]
This feature will be available in upcoming version 2.0.6, thank you for your suggestion!
![image](https://user-images.githubusercontent.com/26776624/183723056-79b8be2f-8f7e-4045-8fc2-a84c2a3980a2.png)
