### ISSUE TITLE
Suggestions for next version - border + background thresholds

### ISSUE THREAD

**Issue by patriziomadferitmilione** [LucasArona/larona-epict-panel#54]
Hi,

love your plugin, would love the possibility of more features:

- apply borders to the metrics and change style and color to them;
- apply thresholds to the metrics' background colors;
- colorize the custom symbols too (only tried png types, will try with SVG and other types to see if not already possible)

Thanks for the great work :)

**Comment by LucasArona** [comment]
Hello,

thanks for you feedback and for your suggestions!
You should already be able to colorize custom symbols, however only svg symbols were tested.
