### ISSUE TITLE
Cannot install epict panel 

### ISSUE THREAD

**Issue by JuergenPi** [LucasArona/larona-epict-panel#61]
If I try the command
pi@raspberrypi:~ $ sudo grafana-cli plugins install larona-epict-panel
(copy from grafana.com)

then I will get the responce

installing larona-epict-panel @ 2.0.4
from: https://grafana.com/api/plugins/larona-epict-panel/versions/2.0.4/download
into: /var/lib/grafana/plugins
Error: ✗ failed to extract plugin archive: failed to extract file: failed to open file: open /var/lib/grafana/plugins/larona-epict-panel/img/logo.svg: no such file or directory

With other panaels I have no problem with installing.
What is my mistake?

**Comment by LucasArona** [comment]
This issue was fixed in Grafana 7.2.0, please ensure you are running a current version of Grafana
